version: "3.8"

services:
  users-microservice:
    build: '../users-microservice'
    container_name: users-microservice
    ports:
      - 3000:3000
    env_file:
      - 'env/users-service.env'
    restart: always
    depends_on:
      localstack:
        condition: service_healthy
      postgres:
        condition: service_started

  notifications-microservice:
    build: '../notifications-microservice'
    container_name: notifications-microservice
    ports:
      - 4000:4000
    env_file:
      - 'env/notif-service.env'
    restart: always
    depends_on:
      localstack:
        condition: service_healthy

  localstack:
    container_name: 'localstack'
    image: localstack/localstack:3.5.0
    ports:
      - "4566:4566"  # LocalStack Gateway
      - "4575:4575"  # SNS
      - "4576:4576"  # SQS
    env_file:
      - 'env/localstack.env'
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-../localstack}:/var/lib/localstack'
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh

  postgres:
    container_name: postgres
    image: postgres:16.3-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - 'env/postgres.env'
    volumes:
      - '${POSTGRES_VOLUME_DIR:-../data}:/var/lib/postgresql/data'